package renamer.client.options;

import java.io.File;
import javax.swing.DefaultComboBoxModel;
import javax.swing.DefaultListModel;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import renamer.client.main.GUIForm;
import renamer.server.options.OptionsData;
import renamer.server.options.OptClass;
import renamer.server.options.FileOptions;

/**
 *
 * @author Matt-3
 */
public class Options extends javax.swing.JFrame {
    private static GUIForm parent;
    
    public static void setParent(GUIForm parent){
        Options.parent = parent;
    }
    
    public Options() {
        initComponents();
        this.listModel = new DefaultListModel();
        OptClass op = GUIForm.getOptions();
        unpackOptions(op);
        buttonSave.setEnabled(false);
        jFile.setCurrentDirectory(new File(op.getDefaultDirectory()));
    }
    
    private void initGeneralOptions(OptClass op){
      txtDefaultDir.setText(op.getDefaultDirectory()); 
    }
    
    private void initFilterOptions(OptClass op){
        
    }
    
    private void initSubtitleOptions(OptClass op){
        languageCMB.setSelectedIndex(op.getLanguageIndex());
        txtSubTag.setText(op.getLanguageTag());
    }
    
    private void unpackOptions(OptClass opt){
        initGeneralOptions(opt);
        initFilterOptions(opt);
        initSubtitleOptions(opt);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jFile = new javax.swing.JFileChooser();
        buttonSave = new javax.swing.JButton();
        buttonCancel = new javax.swing.JButton();
        buttonClose = new javax.swing.JButton();
        tabbedPanel = new javax.swing.JTabbedPane();
        panelGeneral = new javax.swing.JPanel();
        txtDefaultDir = new javax.swing.JTextField();
        buttonSetDir = new javax.swing.JButton();
        lblCurrentDir = new javax.swing.JLabel();
        panelFilter = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        listCustom = new javax.swing.JList();
        lblCustom = new javax.swing.JLabel();
        buttonAdd = new javax.swing.JButton();
        buttonRemove = new javax.swing.JButton();
        listCustomFilter = new java.awt.List();
        jLabel1 = new javax.swing.JLabel();
        panelSubs = new javax.swing.JPanel();
        languageCMB = new javax.swing.JComboBox();
        jLabel2 = new javax.swing.JLabel();
        txtSubTag = new javax.swing.JTextField();
        jCheckBox1 = new javax.swing.JCheckBox();
        buttonDefault = new javax.swing.JButton();

        jFile.setDialogTitle("\"Choose a Folder To Open\"");
        jFile.setFileSelectionMode(javax.swing.JFileChooser.DIRECTORIES_ONLY);

        setTitle("Options");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
        });

        buttonSave.setText("Apply");
        buttonSave.setEnabled(false);
        buttonSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonSaveActionPerformed(evt);
            }
        });

        buttonCancel.setText("Cancel");
        buttonCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonCancelActionPerformed(evt);
            }
        });

        buttonClose.setText("Close");
        buttonClose.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonCloseActionPerformed(evt);
            }
        });

        txtDefaultDir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                txtDefaultDirMouseReleased(evt);
            }
        });
        txtDefaultDir.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                txtDefaultDirPropertyChange(evt);
            }
        });
        txtDefaultDir.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtDefaultDirKeyReleased(evt);
            }
        });

        buttonSetDir.setText("Set New Directory");
        buttonSetDir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonSetDirActionPerformed(evt);
            }
        });

        lblCurrentDir.setText("Current Default Directory:");

        javax.swing.GroupLayout panelGeneralLayout = new javax.swing.GroupLayout(panelGeneral);
        panelGeneral.setLayout(panelGeneralLayout);
        panelGeneralLayout.setHorizontalGroup(
            panelGeneralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblCurrentDir, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(panelGeneralLayout.createSequentialGroup()
                .addComponent(txtDefaultDir, javax.swing.GroupLayout.PREFERRED_SIZE, 236, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(buttonSetDir)
                .addGap(0, 65, Short.MAX_VALUE))
        );
        panelGeneralLayout.setVerticalGroup(
            panelGeneralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelGeneralLayout.createSequentialGroup()
                .addComponent(lblCurrentDir, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelGeneralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtDefaultDir, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(buttonSetDir))
                .addContainerGap(299, Short.MAX_VALUE))
        );

        tabbedPanel.addTab("General", panelGeneral);

        jScrollPane1.setViewportView(listCustom);

        lblCustom.setText("Custom Filters:");

        buttonAdd.setText("Add Filter");
        buttonAdd.setEnabled(false);
        buttonAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonAddActionPerformed(evt);
            }
        });

        buttonRemove.setText("Remove Filter");
        buttonRemove.setEnabled(false);

        listCustomFilter.setEnabled(false);

        jLabel1.setText("Default Media Types:");

        javax.swing.GroupLayout panelFilterLayout = new javax.swing.GroupLayout(panelFilter);
        panelFilter.setLayout(panelFilterLayout);
        panelFilterLayout.setHorizontalGroup(
            panelFilterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelFilterLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelFilterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(listCustomFilter, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblCustom)
                    .addComponent(buttonRemove, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(buttonAdd, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 199, Short.MAX_VALUE)
                .addGroup(panelFilterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addContainerGap())
        );
        panelFilterLayout.setVerticalGroup(
            panelFilterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelFilterLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelFilterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCustom)
                    .addComponent(jLabel1))
                .addGap(7, 7, 7)
                .addGroup(panelFilterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 234, Short.MAX_VALUE)
                    .addComponent(listCustomFilter, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(5, 5, 5)
                .addComponent(buttonAdd)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(buttonRemove)
                .addContainerGap(24, Short.MAX_VALUE))
        );

        tabbedPanel.addTab("Filters", panelFilter);

        languageCMB.setModel(new DefaultComboBoxModel(renamer.server.options.OptionsData.LANGUAGES));
        languageCMB.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                languageCMBItemStateChanged(evt);
            }
        });

        jLabel2.setText("Prefered Language:");

        txtSubTag.setEnabled(false);

        jCheckBox1.setText("Use Custom Tag");
        jCheckBox1.setEnabled(false);

        javax.swing.GroupLayout panelSubsLayout = new javax.swing.GroupLayout(panelSubs);
        panelSubs.setLayout(panelSubsLayout);
        panelSubsLayout.setHorizontalGroup(
            panelSubsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelSubsLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelSubsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(languageCMB, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, panelSubsLayout.createSequentialGroup()
                        .addComponent(jCheckBox1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtSubTag, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap(274, Short.MAX_VALUE))
        );
        panelSubsLayout.setVerticalGroup(
            panelSubsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelSubsLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(languageCMB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelSubsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jCheckBox1)
                    .addComponent(txtSubTag, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(263, Short.MAX_VALUE))
        );

        tabbedPanel.addTab("Subtitles", panelSubs);

        buttonDefault.setText("Reset All Settings");
        buttonDefault.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonDefaultActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(tabbedPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(buttonDefault)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(104, 104, 104)
                        .addComponent(buttonSave)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(buttonClose)
                        .addGap(76, 76, 76))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(buttonCancel)
                        .addGap(5, 5, 5))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(tabbedPanel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(buttonSave)
                    .addComponent(buttonCancel)
                    .addComponent(buttonClose)
                    .addComponent(buttonDefault))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void buttonSetDirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonSetDirActionPerformed
        int returnVal = jFile.showOpenDialog(Options.this);
        if (returnVal == JFileChooser.APPROVE_OPTION) {
            File folder = jFile.getSelectedFile();
            String f = folder.getAbsolutePath();
            if (!f.equals(txtDefaultDir.getText())) {
                txtDefaultDir.setText(f);
                buttonSave.setEnabled(true);
            }
        } else {
            System.out.println("Open command cancelled by user.");
        }
    }//GEN-LAST:event_buttonSetDirActionPerformed

    private void buttonCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonCancelActionPerformed
        parent.setEnabled(true);
        parent.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_buttonCancelActionPerformed

    private OptClass saveGeneralPanel(OptClass opt){
        opt.setDefaultDirectory(txtDefaultDir.getText());
        return opt;
    }
    
    private OptClass saveFilterPanel(OptClass opt){
        return opt;
    }
    
    private OptClass saveSubtitlesPanel(OptClass opt){
        opt.setSelectedLanguage(languageCMB.getSelectedIndex());
        return opt;
    }
    
    private void buttonSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonSaveActionPerformed
        
        OptClass options = GUIForm.getOptions();
        options = saveGeneralPanel(options);
        options = saveFilterPanel(options);
        options = saveSubtitlesPanel(options);
        jFile.setCurrentDirectory(new File(options.getDefaultDirectory()));
        if (FileOptions.saveOpt(options)){
            //System.out.println("Options Saved.");
        } else {
            //System.out.println("Options Could Not Be Saved.");
        }
        GUIForm.setOptions(options);
        buttonSave.setEnabled(false);
    }//GEN-LAST:event_buttonSaveActionPerformed

    private void buttonCloseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonCloseActionPerformed
        parent.setEnabled(true);
        parent.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_buttonCloseActionPerformed

    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed
    }//GEN-LAST:event_formWindowClosed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        parent.setEnabled(true);
        parent.setVisible(true);
    }//GEN-LAST:event_formWindowClosing

    private void txtDefaultDirPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_txtDefaultDirPropertyChange
        buttonSave.setEnabled(true);
    }//GEN-LAST:event_txtDefaultDirPropertyChange

    private void txtDefaultDirMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtDefaultDirMouseReleased

    }//GEN-LAST:event_txtDefaultDirMouseReleased

    private void txtDefaultDirKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtDefaultDirKeyReleased
        buttonSave.setEnabled(true);
    }//GEN-LAST:event_txtDefaultDirKeyReleased

    private void buttonAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonAddActionPerformed
        listCustomFilter.add("");
    }//GEN-LAST:event_buttonAddActionPerformed

    private void languageCMBItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_languageCMBItemStateChanged
        buttonSave.setEnabled(true);
        txtSubTag.setText(OptionsData.LANGUAGETAGS[languageCMB.getSelectedIndex()]);
    }//GEN-LAST:event_languageCMBItemStateChanged

    private void buttonDefaultActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonDefaultActionPerformed
        int res = JOptionPane.showConfirmDialog(this, "This will reset all options to the defaults, are you sure you want to continue?\nThis Cannot be undone.", "Do You Wish To Reset User Options?", JOptionPane.YES_NO_OPTION);
        if (res == JOptionPane.YES_OPTION){
            OptClass opt = FileOptions.createDefaultOptionsFile();
            if (opt == null){
                //clean up if there is a failure to put things back the way they were?
                JOptionPane.showMessageDialog(this, "There was an error resetting the options to default.", "Error resetting options.", JOptionPane.ERROR_MESSAGE);
            } else {
                System.out.println("Options reset to default.");
                GUIForm.setOptions(opt);
                jFile.setCurrentDirectory(new File(opt.getDefaultDirectory()));
                unpackOptions(opt);
                buttonSave.setEnabled(false);
            }
        }
    }//GEN-LAST:event_buttonDefaultActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Options.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Options.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Options.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Options.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Options().setVisible(true);
            }
        });
    }
    
    private DefaultListModel listModel;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonAdd;
    private javax.swing.JButton buttonCancel;
    private javax.swing.JButton buttonClose;
    private javax.swing.JButton buttonDefault;
    private javax.swing.JButton buttonRemove;
    private javax.swing.JButton buttonSave;
    private javax.swing.JButton buttonSetDir;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JFileChooser jFile;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JComboBox languageCMB;
    private javax.swing.JLabel lblCurrentDir;
    private javax.swing.JLabel lblCustom;
    private javax.swing.JList listCustom;
    private java.awt.List listCustomFilter;
    private javax.swing.JPanel panelFilter;
    private javax.swing.JPanel panelGeneral;
    private javax.swing.JPanel panelSubs;
    private javax.swing.JTabbedPane tabbedPanel;
    private javax.swing.JTextField txtDefaultDir;
    private javax.swing.JTextField txtSubTag;
    // End of variables declaration//GEN-END:variables
}
